[tool.poetry]
name = "20-1"
version = "0.1.0"
description = ""
authors = ["NazKar@Nazir <karimov.nazir00@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg2-binary = "^2.9.10"
black = "^25.1.0"
pillow = "^11.2.1"
ipython = "^9.2.0"
dotenv = "^0.9.9"
psycopg2 = "^2.9.10"
python-dotenv = "^1.1.0"
django = "4.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
