# Generated by Django 5.2 on 2025-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, если пост опубликован",
                verbose_name="Опубликовано",
            ),
        ),
    ]
